### ISSUE TITLE
Actions are run multiple times

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/MusicBot-API#30]
Pull Requests from branches are run multiple times.

Possible fix:
```yaml
on: 
  push:
    branches: master
  pull_request:
```

This would however exclude branches without pull request
